//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zTest2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zTest2DBEntities : DbContext
    {
        public zTest2DBEntities()
            : base("name=zTest2DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblCategory> TblCategories { get; set; }
        public virtual DbSet<TblDevice> TblDevices { get; set; }
        public virtual DbSet<TblShop> TblShops { get; set; }
        public virtual DbSet<TblUser> TblUsers { get; set; }
        public virtual DbSet<TblCart> TblCarts { get; set; }
        public virtual DbSet<TblCartItem> TblCartItems { get; set; }
        public virtual DbSet<TblReceipt> TblReceipts { get; set; }
    }
}
