//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zTest2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCartItem
    {
        public int CartId { get; set; }
        public int DeviceId { get; set; }
        public int Amount { get; set; }
    
        public virtual TblCart TblCart { get; set; }
        public virtual TblDevice TblDevice { get; set; }
    }
}
