//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zTest2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblReceipt
    {
        public int Receiptld { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public Nullable<int> Tax { get; set; }
        public Nullable<int> PriceWithTax { get; set; }
        public Nullable<System.DateTime> DateAndTime { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual TblDevice TblDevice { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
